### PR TITLE
Update wikiEntry.h (add < operator)

### PR DESCRIPTION
**Pull request by luanluc42**
C:\Users\douch\wikiDataProject\wikiDataProject\Spikes\wikiEntrySpike\wikiEntry.h

### CODE REVIEW

**Comment by emilyastranova** [comment]
Use stoi() when doing pairType comparison, strings can't compare like ints. Will recently found that out

**Comment by luanluc42** [comment]
C:\Users\douch\wikiDataProject\wikiDataProject\Spikes\wikiEntrySpike\wikiEntry.h
How about this, tyler?

**Comment by emilyastranova** [comment]
Change your && to || (or instead of and) and that code will work 👍

**Comment by luanluc42** [comment]
C:\Users\douch\wikiDataProject\wikiDataProject\Spikes\wikiEntrySpike\wikiEntry.h
This will do

**Pull request merged**
